Desktop/book-finder/backend/config/routes.rb
Rails.application.routes.draw do
  resources :favorites
    post '/favorites', to: 'favorites#create'
  resources :users
  # get '/books', to: 'books#get_books'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/book-finder/backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Desktop/book-finder/backend/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
end

Desktop/book-finder/backend/app/models/user.rb
class User < ApplicationRecord
end

Desktop/book-finder/backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

Desktop/book-finder/backend/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  def index
    puts params
    @favorites = Favorite.all
    render json: @favorites

  end

  # GET /favorites/1
  def show
    render json: @favorite
  end

  # # GET /favorites/new
  # def new
  #   @favorite = Favorite.new
  # end

  # # GET /favorites/1/edit
  # def edit
  # end

  # POST /favorites
  def create
  favorite = Favorite.new(favorite_params)
  if favorite.save!
    render json: favorite
  else
    render :new
  end
end

  # PATCH/PUT /favorites/1
  def update
    if @favorite.update(favorite_params)
      redirect_to @favorite, notice: 'Favorite was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /favorites/1
  def destroy
    @favorite.destroy
    redirect_to favorites_url, notice: 'Favorite was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :book_string, :title, :authors, :image_url)
    end
end

Desktop/book-finder/backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    render json: @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name)
    end
end

Desktop/book-finder/backend/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Desktop/book-finder/backend/app/helpers/users_helper.rb
module UsersHelper
end

Desktop/book-finder/backend/app/views/favorites/_form.html.erb
<%= form_with(model: favorite, local: true) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :stars %>
    <%= form.number_field :stars %>
  </div>

  <div class="field">
    <%= form.label :number_of_reviews %>
    <%= form.number_field :number_of_reviews %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Desktop/book-finder/backend/app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

Desktop/book-finder/backend/app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Year</th>
      <th>Stars</th>
      <th>Number of reviews</th>
      <th>Image url</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.title %></td>
        <td><%= favorite.author %></td>
        <td><%= favorite.year %></td>
        <td><%= favorite.stars %></td>
        <td><%= favorite.number_of_reviews %></td>
        <td><%= favorite.image_url %></td>
        <td><%= favorite.details %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

Desktop/book-finder/backend/app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

Desktop/book-finder/backend/app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @favorite.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @favorite.author %>
</p>

<p>
  <strong>Year:</strong>
  <%= @favorite.year %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @favorite.stars %>
</p>

<p>
  <strong>Number of reviews:</strong>
  <%= @favorite.number_of_reviews %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @favorite.image_url %>
</p>

<p>
  <strong>Details:</strong>
  <%= @favorite.details %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

Desktop/book-finder/backend/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Desktop/book-finder/backend/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Desktop/book-finder/backend/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Desktop/book-finder/backend/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Desktop/book-finder/backend/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>